language: node_js
node_js:
    - "0.10"
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
    - export CHROME_BIN='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
    - gulp scripts